/**
 * Spec-Kit 增强功能
 * 参考: specs/004-project-cli-commands/contracts/project-init.md
 */

import path from 'path';
import { execa } from 'execa';
import { fileExists, readProjectFile, atomicWriteFile } from '../fs.js';
import { DependencyError } from '../../types/project.js';

/**
 * 检查 speckit CLI 是否可用
 */
export async function checkSpeckitAvailable(): Promise<boolean> {
  try {
    await execa('speckit', ['--version']);
    return true;
  } catch {
    return false;
  }
}

/**
 * 增强 Claude 命令文件,支持自定义分支规则参数
 * @param projectRoot 项目根目录
 * @param branchPrefix 可选的默认分支前缀
 */
export async function enhanceClaudeCommand(
  projectRoot: string,
  branchPrefix?: string
): Promise<boolean> {
  const commandPath = path.join(projectRoot, '.claude/commands/speckit.plan.md');

  if (!(await fileExists(commandPath))) {
    console.warn(`警告: 未找到 ${commandPath},跳过命令增强`);
    return false;
  }

  try {
    const content = await readProjectFile(commandPath, projectRoot);

    // 检查是否已经增强过
    if (content.includes('## 自定义分支规则')) {
      console.log('Claude 命令已经增强过,跳过');
      return true;
    }

    // 注入增强内容
    const enhancement = `

## 自定义分支规则(可选)

用户可以在执行 \`/speckit.plan\` 时指定自定义分支规则,格式如下:

\`\`\`text
/speckit.plan 分支前缀为 feature/
/speckit.plan 分支命名模式为 ^feat-[a-z0-9-]+$
\`\`\`

当检测到这些参数时,在创建分支时应用相应规则。

${branchPrefix ? `默认分支前缀: \`${branchPrefix}\`\n` : ''}`;

    // 在 ## Outline 之前注入
    const enhancedContent = content.replace(/## Outline/, `${enhancement}\n## Outline`);

    await atomicWriteFile(commandPath, enhancedContent, projectRoot);
    console.log(`✅ 已修改 /speckit.plan 命令以支持自定义分支规则`);
    return true;
  } catch (error) {
    console.error(`增强 Claude 命令失败: ${error}`);
    return false;
  }
}

/**
 * 在 CLAUDE.md 中注入宪章约束
 * @param projectRoot 项目根目录
 */
export async function injectConstitutionConstraints(projectRoot: string): Promise<boolean> {
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');

  // 检查宪章文件是否存在
  const constitutionPaths = [
    path.join(projectRoot, '.specify/memory/constitution.md'),
    path.join(projectRoot, 'constitution.md'),
  ];

  let constitutionPath: string | undefined;
  for (const p of constitutionPaths) {
    if (await fileExists(p)) {
      constitutionPath = path.relative(projectRoot, p);
      break;
    }
  }

  if (!constitutionPath) {
    console.warn('警告: 未找到宪章文件,跳过约束注入');
    return false;
  }

  // 检查 CLAUDE.md 是否存在
  if (!(await fileExists(claudeMdPath))) {
    console.warn(`警告: 未找到 ${claudeMdPath},跳过约束注入`);
    return false;
  }

  try {
    const content = await readProjectFile(claudeMdPath, projectRoot);

    // 检查是否已经注入过
    if (content.includes('## Constitution Constraints')) {
      console.log('CLAUDE.md 已经注入宪章约束,跳过');
      return true;
    }

    // 构建注入内容
    const injection = `

## Constitution Constraints

This project follows the Spec-Kit constitution defined in \`${constitutionPath}\`.
All code generated by Claude MUST comply with the principles and rules in the constitution.

Key principles:
- Follow the architectural patterns and technology constraints defined in the constitution
- Ensure all implementations align with the project's core values and quality standards
- Validate design decisions against constitution principles before implementation

Before making any architectural decisions, verify compliance with the constitution.
`;

    // 在 ## Project Architecture 之前注入,如果找不到则在 ## Project Overview 之后注入
    let enhancedContent: string;
    if (content.includes('## Project Architecture')) {
      enhancedContent = content.replace(/## Project Architecture/, `${injection}\n## Project Architecture`);
    } else if (content.includes('## Project Overview')) {
      enhancedContent = content.replace(
        /(## Project Overview[\s\S]*?)(\n## )/,
        `$1${injection}$2`
      );
    } else {
      // 如果两个标题都不存在,追加到文件末尾
      enhancedContent = content + injection;
    }

    await atomicWriteFile(claudeMdPath, enhancedContent, projectRoot);
    console.log(`✅ 已在 CLAUDE.md 中注入宪章约束`);
    return true;
  } catch (error) {
    console.error(`注入宪章约束失败: ${error}`);
    return false;
  }
}

/**
 * 执行 speckit init
 * @param projectRoot 项目根目录
 * @param verbose 是否显示详细输出
 */
export async function runSpeckitInit(projectRoot: string, verbose: boolean = false): Promise<void> {
  // 检查 speckit 是否可用
  const isAvailable = await checkSpeckitAvailable();
  if (!isAvailable) {
    throw new DependencyError(
      '未找到 speckit CLI\n💡 请先安装 speckit CLI: npm install -g @speckit/cli'
    );
  }

  if (verbose) {
    console.log('⏳ 执行 speckit init...');
  }

  try {
    await execa('speckit', ['init'], {
      cwd: projectRoot,
      stdio: verbose ? 'inherit' : 'pipe',
    });

    if (verbose) {
      console.log('✅ speckit init 完成');
    }
  } catch (error: any) {
    throw new DependencyError(`speckit init 执行失败: ${error.message}`);
  }
}

/**
 * 检查项目是否已经初始化
 */
export async function isProjectInitialized(projectRoot: string): Promise<boolean> {
  const specifyDir = path.join(projectRoot, '.specify');
  return fileExists(specifyDir);
}
